### ISSUE TITLE
How to calculate "simple integration" in Chapter 3

### ISSUE THREAD

**Issue by hihunjin** [google/bi-tempered-loss#10]
![image](https://user-images.githubusercontent.com/32363064/110590239-e0c77400-81ba-11eb-99a6-cc393ea101bc.png)
This image is from your paper.
You said "Via simple integration, ...".
I did it by myself but the constant term $\frac{1}{2-t}$ is ambiguous.
How did you get this term? What constraint did you apply?

**Comment by eamid** [comment]
We set the constant such that the limit t -> 2 exists and gives:

F_2(y) = sum_i (y_i - log y_i - 1)

This convex function induces the Itakura-Saito (aka Burg) divergence.
