### ISSUE TITLE
loss_test.py fails in test_gradient_error

### ISSUE THREAD

**Issue by tatianaosokin** [google/bi-tempered-loss#2]
Hello,
When I tried to change the values of t1 and t2 in loss_test.py line 98 (test_gradient_error function)to be:
t1 = 0.5
t2 = 1.0
instead
t1 = 0.5
t2 = 1.5
The test failed.
Here is the ERROR message:
Traceback (most recent call last):
  File "/home/tanya/code/loss_test.py", line 123, in test_gradient_error
    activations, labels, 0.5, 1.0)
  File "/home/tanya/code/bitempered_loss/loss.py", line 174, in _internal_bi_tempered_logistic_loss
    beta = 1.0 + one_minus_t1
UnboundLocalError: local variable 'one_minus_t1' referenced before assignment

It looks like the one_minus_t1 is calculated only in case that t2>1.0, and so it fails when t2=1.0 and t1<1.0

Thanks.

**Comment by eamid** [comment]
This issue should be fixed with the recent changes. Thank you for bringing this to our attention!
