### ISSUE TITLE
How are the labels corrupted?

### ISSUE THREAD

**Issue by Charles-Xie** [google/bi-tempered-loss#5]
Hi, I'm trying to reproduce your experiments on cifar100.
For label noise experiments, it's mentioned in paper that

> we introduce noise by artificially corrupting a fraction of the labels and producing a new set of labels for each noise level.

But I'm still not sure how to **corrupt** these labels exactly. Are these labels shuffled or what? I hope that you can give me a few more instructions on this, a few lines of code will be the best. 

Thanks a lot.

**Comment by eamid** [comment]
Hi,

We make sure that the noisy label is set to a class other than the true class. You can try this piece of code to generate the noise:

noisy_labels = (noisy_labels + np.random.uniform(low=1, high=num_classes, size=num_noisy_examples)) % num_classes

**Comment by Charles-Xie** [comment]
@eamid That helps. Thank you!
