### ISSUE TITLE
why 5 is the default num_iters?

### ISSUE THREAD

**Issue by wuyuanhang94** [google/bi-tempered-loss#8]
cannot understand why existing a while with 5 as iteration time of method, since nothwhere including the original paper mentions this super parameter.

**Comment by eamid** [comment]
We noticed usually 5 iterations is sufficient for Algorithm 1 in the paper to converge (even for large number of classes ~30k). You can increase this number if you need. However in all our experiments, we use 5 iterations.

**Comment by rohan-anil** [comment]
We can possibly increase this to say 100, and write an early exit which will be robust.

**Comment by wuyuanhang94** [comment]
thanks, closing this issue.
